# Generated by Django 5.0.6 on 2024-11-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routes',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
