# Generated by Django 5.0.6 on 2024-11-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='agent_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='delivery_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='routes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
