# Generated by Django 5.0.6 on 2024-11-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_routes_agent_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='co_emission',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
