# Generated by Django 5.0.6 on 2024-11-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_routes_co_emission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='co_emission',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
