# Generated by Django 5.0.6 on 2024-11-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_routes_co_emission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='speed',
        ),
        migrations.AddField(
            model_name='routes',
            name='route_pref',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
